package fotchat.pogos;
// Generated Mar 25, 2023 2:43:15 PM by Hibernate Tools 4.3.1



/**
 * Files generated by hbm2java
 */
public class Files  implements java.io.Serializable {


     private Integer id;
     private int chatid;
     private String link;
     private int isDeleted;

    public Files() {
    }

    public Files(int chatid, String link, int isDeleted) {
       this.chatid = chatid;
       this.link = link;
       this.isDeleted = isDeleted;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getChatid() {
        return this.chatid;
    }
    
    public void setChatid(int chatid) {
        this.chatid = chatid;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

    public void setChatId(int chatId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


