package fotchat.pogos;
// Generated Mar 25, 2023 2:43:15 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String nicname;
     private String email;
     private String avatar;
     private int isDeleted;
     private String password;
     private int roleId;

    public User() {
    }

    public User(String username, String nicname, String email, String avatar, int isDeleted, String password, int roleId) {
       this.username = username;
       this.nicname = nicname;
       this.email = email;
       this.avatar = avatar;
       this.isDeleted = isDeleted;
       this.password = password;
       this.roleId = roleId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getNicname() {
        return this.nicname;
    }
    
    public void setNicname(String nicname) {
        this.nicname = nicname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    public void setAvatar(byte[] avatarImage) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setNickname(String nickname) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


