package chatapp.db;
// Generated Mar 25, 2023 1:25:06 AM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String username;
     private String password;
     private String nickname;
     private String profilephoto;

    public Users() {
    }

    public Users(String email, String username, String password, String nickname, String profilephoto) {
       this.email = email;
       this.username = username;
       this.password = password;
       this.nickname = nickname;
       this.profilephoto = profilephoto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getProfilephoto() {
        return this.profilephoto;
    }
    
    public void setProfilephoto(String profilephoto) {
        this.profilephoto = profilephoto;
    }




}


